### ISSUE TITLE
Symbolic Icons Instead of Regular Ones

### ISSUE THREAD

**Issue by verrannt** [mdh34/elementary-indicators#14]
I'm on EOS 5.1 Hera and the indicator fix is working flawlessly. Thanks for that!

I'm wondering if one can change the regular icons that are being used for the app indicators to symbolic ones.

To the best of my knowledge, this should be possible in the `gtk.css` or `gtk-widgets.css` files accompanying a given theme. To be theme-independent, I've successfully tried [this fix](https://github.com/mdh34/elementary-indicators/issues/1#issuecomment-560757367) for fixing the issue regarding gaps between indicators. To get symbolic icons, I've additionally added `-gtk-icon-style: symbolic;` to the the `.composited-indicator` class like so:

 ```css
/* file ~/.config/gtk-3.0/gtk.css */
.composited-indicator {
    padding: 0 2px;
    -gtk-icon-style: symbolic;
}
```

… but unfortunately this does not do the trick. Does anyone have an idea how this could be done?
